name: butterfly
description: Powerful, minimalistic, cross-platform, opensource note-taking app

publish_to: none

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.0-alpha.0+59

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  butterfly_api:
    path: ../api
  flutter_svg: ^2.0.2
  flutter_bloc: ^8.1.2
  image: ^4.0.15
  intl: ^0.17.0
  path_provider: ^2.0.11
  shared_preferences: ^2.0.18
  url_launcher: ^6.1.10
  file_picker: ^5.2.5
  phosphor_flutter: ^1.4.0
  replay_bloc: ^0.2.3
  share_plus: ^6.3.1
  package_info_plus: ^3.0.3
  idb_shim: ^2.3.0+1
  go_router: ^6.2.0
  xml: ^6.2.2
  collection: ^1.17.1
  bloc_concurrency: ^0.2.1
  camera: ^0.10.3+1
  camera_windows: ^0.2.1+5
  window_manager: ^0.3.0
  flex_color_scheme: ^7.0.0-dev.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  path: ^1.8.2
  printing: ^5.10.1
  js: ^0.6.5
  pdf: ^3.9.0
  http: ^0.13.5
  flutter_secure_storage: ^8.0.0
  equatable: ^2.0.5
  adwaita: ^0.5.2
  yaru: ^0.5.5
  rxdart: ^0.27.7
  ffi: ^2.0.1
  archive: ^3.3.6
  animations: ^2.0.7
  connectivity_plus: ^3.0.3
  cross_file: ^0.3.3+4
  args: ^2.4.0
  perfect_freehand:
    git:
      url: https://github.com/CodeDoctorDE/perfect-freehand-dart.git
      ref: 066461ee27342559e5731a03e3371c0537f1abcb
dev_dependencies:
  flutter_native_splash: ^2.2.18
  #flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  analyzer: ^5.6.0
  freezed: ^2.3.2
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  espresso: ^0.2.0+9
dependency_overrides:
  archive: 3.3.6
  collection: 1.17.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Thin.ttf
          weight: 100
        - asset: fonts/Roboto-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: fonts/Roboto-Light.ttf
          weight: 300
        - asset: fonts/Roboto-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/Roboto-Black.ttf
          weight: 900
        - asset: fonts/Roboto-BlackItalic.ttf
          weight: 900
          style: italic
  assets:
    - images/
    - templates/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
