name: butterfly
description: Powerful, minimalistic, cross-platform, opensource note-taking app

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.4.0-beta.1+32

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.1.1+1
  flutter_bloc: ^8.0.1
  image: ^3.2.0
  intl: ^0.17.0
  path_provider: ^2.0.11
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.4
  file_picker: ^4.6.1
  phosphor_flutter: ^1.4.0
  replay_bloc: ^0.2.1
  share_plus: ^4.0.10
  package_info_plus: ^1.4.2
  idb_shim: ^2.0.1+1
  go_router: ^4.1.0
  xml: ^6.0.1
  collection: ^1.16.0
  bloc_concurrency: ^0.2.0
  camera: ^0.9.8+1
  camera_windows: ^0.1.0+2
  window_manager: ^0.2.5
  flex_color_scheme: ^5.1.0
  freezed_annotation: ^2.0.3
  json_annotation: ^4.6.0
  path: ^1.8.1
  printing: ^5.9.1
  js: ^0.6.4
  pdf: ^3.8.1
  http: ^0.13.4
  flutter_secure_storage: ^5.0.2
  equatable: ^2.0.3
  adwaita: ^0.5.2
  yaru: ^0.3.3
  rxdart: ^0.27.4

dev_dependencies:
  flutter_native_splash: ^2.2.4
  flutter_launcher_icons: ^0.9.3
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  analyzer: ^4.2.0
  freezed: ^2.0.4
  build_runner: ^2.1.11
  json_serializable: ^6.3.0
  espresso: ^0.2.0+2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
  assets:
    - images/
    - templates/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
