name: butterfly
description: Powerful, minimalistic, cross-platform, opensource note-taking app

publish_to: none

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.4.0+156

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: 3.35.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  integration_test:
    sdk: flutter
  butterfly_api:
    path: ../api
  flutter_svg: ^2.2.0
  flutter_bloc: ^9.0.0
  intl: any
  path_provider: ^2.1.3
  shared_preferences: ^2.2.3
  url_launcher: ^6.2.6
  file_selector: ^1.0.3
  phosphor_flutter: ^2.1.0
  replay_bloc: ^0.3.0
  share_plus: ^12.0.0
  package_info_plus: ^9.0.0
  idb_shim: ^2.4.1+1
  go_router: ^16.0.0
  xml: ^6.5.0
  collection: ^1.18.0
  bloc_concurrency: ^0.3.0
  camera: ^0.11.0
  camera_windows: ^0.2.1+9
  window_manager: ^0.5.0
  flex_color_scheme: ^8.0.0
  json_annotation: ^4.9.0
  printing: ^5.14.2
  pdf: ^3.11.3
  http: ^1.2.1
  flutter_secure_storage: ^10.0.0-beta.2
  equatable: ^2.0.5
  rxdart: ^0.28.0
  archive: ^4.0.0
  animations: ^2.0.11
  connectivity_plus: ^7.0.0
  cross_file: ^0.3.4+1
  args: ^2.5.0
  reorderable_grid: ^1.0.12
  perfect_freehand: ^2.5.0
  material_leap:
    git:
      url: https://github.com/LinwoodDev/dart_pkgs.git
      ref: 12843672e8f33e9370444b13fca8134f4543f7ee
      path: packages/material_leap
  lw_sysapi:
    git:
      url: https://github.com/LinwoodDev/dart_pkgs.git
      ref: 7a9ebaba930ca39b6d2a4a76ab5056d7fad18a01
      path: packages/lw_sysapi
  networker:
    git:
      url: https://github.com/LinwoodDev/dart_pkgs.git
      ref: 4f221c5943ceb786eb7bd427eb71a8cc1346b9b8
      path: packages/networker/networker
  networker_socket:
    git:
      url: https://github.com/LinwoodDev/dart_pkgs.git
      ref: ec6f31ba3eb0da17bdef6a8d66ef6caafcabd908
      path: packages/networker/networker_socket
  networker_crypto:
    git:
      url: https://github.com/LinwoodDev/dart_pkgs.git
      ref: ec6f31ba3eb0da17bdef6a8d66ef6caafcabd908
      path: packages/networker/networker_crypto
  swamp_api:
    git:
      url: https://github.com/LinwoodDev/Swamp.git
      ref: 1c15259fc8c5e043997ffcaafbf45348a77e3003
      path: api
  lw_file_system:
    git:
      url: https://github.com/LinwoodDev/dart_pkgs.git
      ref: 12843672e8f33e9370444b13fca8134f4543f7ee
      path: packages/lw_file_system
  flutter_localized_locales: ^2.0.5
  cryptography_flutter_plus: ^2.3.4
  dynamic_color: ^1.7.0
  popover: ^0.3.0
  markdown: ^7.2.2
  image: ^4.1.7
  one_dollar_unistroke_recognizer: ^1.2.0
  super_clipboard: ^0.9.0-dev.4
  web: ^1.0.0
  cryptography_plus: ^2.7.1
  barcode: ^2.2.9
  network_info_plus: ^7.0.0
  flutter_math_fork: ^0.7.4
# Does not work currently
#dependency_overrides:
#  irondash_engine_context:
#    git:
#      url: https://github.com/CodeDoctorDE/irondash
#      ref: 65343873472d6796c0388362a8e04b6e9a499044
#      path: engine_context/dart
dev_dependencies:
  #flutter_native_splash: ^2.4.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  build_runner: ^2.7.0
  json_serializable: ^6.7.1
  freezed: ^3.0.2
  msix: ^3.16.9
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  fonts:
    - family: Comfortaa
      fonts:
        - asset: fonts/Comfortaa-Light.ttf
          weight: 300
        - asset: fonts/Comfortaa-Regular.ttf
          weight: 400
        - asset: fonts/Comfortaa-Medium.ttf
          weight: 500
        - asset: fonts/Comfortaa-SemiBold.ttf
          weight: 600
        - asset: fonts/Comfortaa-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Thin.ttf
          weight: 100
        - asset: fonts/Roboto-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: fonts/Roboto-Light.ttf
          weight: 300
        - asset: fonts/Roboto-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/Roboto-Black.ttf
          weight: 900
        - asset: fonts/Roboto-BlackItalic.ttf
          weight: 900
          style: italic
  assets:
    - images/
    - templates/
    - defaults/
    - fonts/Comfortaa-LICENSE.txt
    - fonts/Roboto-LICENSE.txt
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
msix_config:
  display_name: Linwood Butterfly
  publisher_display_name: Linwood Development
  identity_name: LinwoodDevelopment.linwood-butterfly
  logo_path: images/logo.png
  capabilities: internetClientServer, webcam, documentsLibrary
  languages: en-us, af, ar, ca, cs, da, de, el, es, fi, fr, he, hi, hu, it, ja, ko, nl, no, pl, pt-br, pt, ro, ru, sr-Latn, sv, th, tr, uk, vi, zh-Hans, zh-Hant
  file_extension: .bfly, .pdf, .jpg, .jpeg, .png, .gif, .bmp, .ico, .md
  install_certificate: false
