name: butterfly
description: Powerful, minimalistic, cross-platform, opensource note-taking app

publish_to: none

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.1.0-beta.4+98

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  butterfly_api:
    path: ../api
  flutter_svg: ^2.0.10+1
  flutter_bloc: ^8.1.4
  intl: ^0.18.1
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.5
  file_selector: ^1.0.3
  phosphor_flutter:
    git:
      url: https://github.com/CodeDoctorDE/phosphor-flutter
      ref: f370dd2c25d3ea51ffb8f1c7c183bc9f33889c82
  replay_bloc: ^0.2.6
  share_plus: ^8.0.2
  package_info_plus: ^6.0.0
  idb_shim: ^2.4.1+1
  go_router: ^13.2.1
  xml: ^6.5.0
  collection: ^1.18.0
  bloc_concurrency: ^0.2.4
  camera: ^0.10.5+9
  camera_windows: ^0.2.1+9
  window_manager: ^0.3.8
  flex_color_scheme: ^7.3.1
  json_annotation: ^4.8.1
  path: ^1.8.3
  printing: ^5.12.0
  js: ^0.7.1
  pdf: ^3.10.8
  http: ^1.2.1
  flutter_secure_storage: ^9.0.0
  equatable: ^2.0.5
  rxdart: ^0.27.7
  archive: ^3.4.10
  animations: ^2.0.11
  connectivity_plus: ^6.0.1
  cross_file: ^0.3.4+1
  args: ^2.4.2
  perfect_freehand:
    git:
      url: https://github.com/CodeDoctorDE/perfect-freehand-dart.git
      ref: 066461ee27342559e5731a03e3371c0537f1abcb
  material_leap:
    git:
      url: https://github.com/LinwoodDev/dart_pkgs.git
      ref: f6161499b096f1d0bf55acbd0f6d8a58330a40e6
      path: packages/material_leap
  lw_sysapi:
    git:
      url: https://github.com/LinwoodDev/dart_pkgs.git
      ref: 9338503df442df2e9a156511de1e93dfee8c4257
      path: packages/lw_sysapi
  networker:
    git:
      url: https://github.com/LinwoodDev/dart_pkgs.git
      ref: 51e8e6e0f3531c35f9d4f34f04ac1235e74fea9b
      path: packages/networker/networker
  networker_socket:
    git:
      url: https://github.com/LinwoodDev/dart_pkgs.git
      ref: 75b5ec0e51096ae169df3cd4f02c9f6affe22a81
      path: packages/networker/networker_socket
  flutter_localized_locales: ^2.0.5
  dynamic_color: ^1.7.0
  popover: ^0.3.0
  markdown: ^7.2.2
  device_info_plus: ^10.0.1
  image: ^4.1.7
  one_dollar_unistroke_recognizer: ^1.0.0
dev_dependencies:
  flutter_native_splash: ^2.4.0
  #flutter_launcher_icons: ^0.11.0
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  espresso: ^0.3.0+7
  freezed: ^2.4.7
dependency_overrides:
  flutter_secure_storage_web:
    git:
      url: https://github.com/ThexXTURBOXx/flutter_secure_storage.git
      ref: 6ac827e457393b5c654c1abda40d31e2cb93f62c
      path: flutter_secure_storage_web
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  fonts:
    - family: Comfortaa
      fonts:
        - asset: fonts/Comfortaa-Light.ttf
          weight: 300
        - asset: fonts/Comfortaa-Regular.ttf
          weight: 400
        - asset: fonts/Comfortaa-Medium.ttf
          weight: 500
        - asset: fonts/Comfortaa-SemiBold.ttf
          weight: 600
        - asset: fonts/Comfortaa-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Thin.ttf
          weight: 100
        - asset: fonts/Roboto-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: fonts/Roboto-Light.ttf
          weight: 300
        - asset: fonts/Roboto-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/Roboto-Black.ttf
          weight: 900
        - asset: fonts/Roboto-BlackItalic.ttf
          weight: 900
          style: italic
  assets:
    - images/
    - templates/
    - defaults/
    - fonts/Comfortaa-LICENSE.txt
    - fonts/Roboto-LICENSE.txt
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
