name: butterfly_api
description: The Linwood Butterfly API
version: 2.2.3-rc.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  archive: ^3.4.10
  collection: ^1.18.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.9.0
  replay_bloc: ^0.2.7
  rxdart: ^0.28.0
  uuid: ^4.4.0
  xml: ^6.5.0
  lw_file_system_api:
    git:
      url: https://github.com/LinwoodDev/dart_pkgs
      path: packages/lw_file_system_api
      ref: 44984e1e51d4ba0ed631d2d201e92ea56e112393

dev_dependencies:
  test: ^1.25.3
  json_serializable: ^6.7.1
  build_runner: ^2.4.9
  freezed: ^2.5.2
  lints: ^5.0.0
  analyzer: ^6.3.0
