name: butterfly_api
description: The Linwood Butterfly API
version: 2.0.0-rc.1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  archive: ^3.4.10
  collection: ^1.18.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.9.0
  replay_bloc: ^0.2.7
  rxdart: ^0.27.7
  uuid: ^4.4.0
  xml: ^6.5.0

dev_dependencies:
  test: ^1.25.3
  json_serializable: ^6.7.1
  build_runner: ^2.4.9
  freezed: ^2.5.2
  lints: ^3.0.0
  analyzer: ^6.3.0
