name: butterfly_api
description: The Linwood Butterfly API
version: 2.0.0-alpha.2

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  collection: ^1.17.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
dev_dependencies:
  json_serializable: ^6.6.1
  build_runner: ^2.3.3
  freezed: ^2.3.2
  lints: ^2.0.1
  test: ^1.24.2
