name: butterfly_api
description: The Linwood Butterfly API
version: 2.0.0-rc.3

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  archive: ^3.4.9
  collection: ^1.18.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  replay_bloc: ^0.2.4
  rxdart: ^0.27.7
  test: ^1.24.9
  xml: ^6.4.2
dev_dependencies:
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  freezed: ^2.4.5
  lints: ^3.0.0
  analyzer: ^6.3.0
