name: butterfly_api
description: The Linwood Butterfly API
version: 2.0.3-rc.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  archive: ^3.4.10
  collection: ^1.18.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  replay_bloc: ^0.2.5
  rxdart: ^0.27.7
  xml: ^6.5.0
dev_dependencies:
  test: ^1.25.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.7
  freezed: ^2.4.6
  lints: ^3.0.0
  analyzer: ^6.3.0
