name: Publish to WinGet
on:
  release:
    types: [released]
jobs:
  publish:
    runs-on: windows-latest
    steps:
      - if: ${{ !contains(github.event.release.tag_name, 'beta') && !contains(github.event.release.tag_name, 'alpha') }}
        uses: vedantmgoyal2009/vedantmgoyal2009/winget-pkgs-automation/releaser-action@v1.0.0
        with:
          identifier: LinwoodCloud.Butterfly
          token: ${{ secrets.CI_PAT }}
      - if: ${{ contains(github.event.release.tag_name, 'beta') || contains(github.event.release.tag_name, 'alpha') }}
        uses: vedantmgoyal2009/vedantmgoyal2009/winget-pkgs-automation/releaser-action@v1.0.0
        with:
          identifier: LinwoodCloud.Butterfly.Beta
          version-regex: '(?<=v).*'
          token: ${{ secrets.CI_PAT }}
