name: Publish to WinGet
on:
  release:
    types: [released, prereleased]
jobs:
  publish:
    runs-on: windows-latest
    steps:
      - if: github.event_name == 'released'
        uses: vedantmgoyal2009/vedantmgoyal2009/winget-pkgs-automation/releaser-action@v1.0.0
        with:
          identifier: LinwoodCloud.Butterfly
          token: ${{ secrets.CI_PAT }}
      - if: github.event_name == 'prereleased'
        uses: vedantmgoyal2009/vedantmgoyal2009/winget-pkgs-automation/releaser-action@v1.0.0
        with:
          identifier: LinwoodCloud.Butterfly.Nightly
          version-regex: '(?<=v).*'
          token: ${{ secrets.CI_PAT }}
